/** SWF tag codes (SWF File Format Specification v19). */
export const TagCode = {
  End: 0,
  ShowFrame: 1,
  DefineShape: 2,
  FreeCharacter: 3,
  PlaceObject: 4,
  RemoveObject: 5,
  DefineBits: 6,
  DefineButton: 7,
  JPEGTables: 8,
  SetBackgroundColor: 9,
  DefineFont: 10,
  DefineText: 11,
  DoAction: 12,
  DefineFontInfo: 13,
  DefineSound: 14,
  StartSound: 15,
  DefineButtonSound: 17,
  SoundStreamHead: 18,
  SoundStreamBlock: 19,
  DefineBitsLossless: 20,
  DefineBitsJPEG2: 21,
  DefineShape2: 22,
  DefineButtonCxform: 23,
  Protect: 24,
  PlaceObject2: 26,
  RemoveObject2: 28,
  DefineShape3: 32,
  DefineText2: 33,
  DefineButton2: 34,
  DefineBitsJPEG3: 35,
  DefineBitsLossless2: 36,
  DefineEditText: 37,
  DefineSprite: 39,
  ProductInfo: 41,
  FrameLabel: 43,
  SoundStreamHead2: 45,
  DefineMorphShape: 46,
  DefineFont2: 48,
  ExportAssets: 56,
  ImportAssets: 57,
  EnableDebugger: 58,
  DoInitAction: 59,
  DefineVideoStream: 60,
  VideoFrame: 61,
  DefineFontInfo2: 62,
  DebugID: 63,
  EnableDebugger2: 64,
  ScriptLimits: 65,
  SetTabIndex: 66,
  FileAttributes: 69,
  PlaceObject3: 70,
  ImportAssets2: 71,
  DoABC: 72,
  DefineFontAlignZones: 73,
  CSMTextSettings: 74,
  DefineFont3: 75,
  SymbolClass: 76,
  Metadata: 77,
  DefineScalingGrid: 78,
  DoABC2: 82,
  DefineShape4: 83,
  DefineMorphShape2: 84,
  DefineSceneAndFrameLabelData: 86,
  DefineBinaryData: 87,
  DefineFontName: 88,
  StartSound2: 89,
  DefineBitsJPEG4: 90,
  DefineFont4: 91,
  EnableTelemetry: 93,
  PlaceObject4: 94,
} as const;

export type TagCodeName = keyof typeof TagCode;

const NAMES = new Map<number, string>(Object.entries(TagCode).map(([k, v]) => [v, k]));

export function tagName(code: number): string {
  return NAMES.get(code) ?? `Unknown(${code})`;
}

/** Tags whose body starts with the u16 id of the character they define. */
export const CHARACTER_DEFINING_TAGS: ReadonlySet<number> = new Set([
  TagCode.DefineShape,
  TagCode.DefineBits,
  TagCode.DefineButton,
  TagCode.DefineFont,
  TagCode.DefineText,
  TagCode.DefineSound,
  TagCode.DefineBitsLossless,
  TagCode.DefineBitsJPEG2,
  TagCode.DefineShape2,
  TagCode.DefineShape3,
  TagCode.DefineText2,
  TagCode.DefineButton2,
  TagCode.DefineBitsJPEG3,
  TagCode.DefineBitsLossless2,
  TagCode.DefineEditText,
  TagCode.DefineSprite,
  TagCode.DefineMorphShape,
  TagCode.DefineFont2,
  TagCode.DefineVideoStream,
  TagCode.DefineFont3,
  TagCode.DefineShape4,
  TagCode.DefineMorphShape2,
  TagCode.DefineBinaryData,
  TagCode.DefineBitsJPEG4,
  TagCode.DefineFont4,
]);
